[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "ts-postagger"
version = "0.1.0"
description = "Turkish Part-of-Speech tagger"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Taner Sezer" }]

dependencies = [
    "spacy>=3.8,<4.0",
    "ts-tokenizer"
]


[project.scripts]
ts-postagger = "ts_postagger.cli:main"


[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
where = ["src"]


[tool.setuptools.package-data]
ts_postagger = [
    "model/*",
    "model/**/*"
]

